### ISSUE TITLE
[Error] Distillation script error

### ISSUE THREAD

**Issue by JeremyMorlier** [JeremyMorlier/dinov2#2]
Error when running distillation
Python error :
```
 20240118 11:13:02 419965 dinov2 helpers.py:102] Training  [  3740/625000]  eta: 14 days, 15:35:04  lr: 0.0002 (0.0001)  wd: 0.0400 (0.0400)  mom: 0.9940 (0.9940)  last_layer_lr: 0.0002 (0.0001)  current_batch_size: 512.0000 (512.0000)  total_loss: 11.0651 (11.1501)  dino_local_crops_loss: 9.8582 (9.8921)  dino_global_crops_loss: 1.2323 (1.2365)  koleo_loss: -0.0254 (0.0214)  ibot_loss: -0.0000 (0.0000)  time: 1.639096  data: 0.300450  max mem: 64132
Traceback (most recent call last):
  File "PATH/dinov2/dinov2/train/train_distill.py", line 318, in <module>
    main(args)
  File "PATH/dinov2/dinov2/train/train_distill.py", line 313, in main
    do_train(cfg, model, resume=not args.no_resume)
  File "PATH/dinov2/dinov2/train/train_distill.py", line 290, in do_train
    periodic_checkpointer.step(iteration)
  File "PATH/dinovenv/lib/python3.10/site-packages/fvcore/common/checkpoint.py", line 428, in step
    self.checkpointer.save(
  File "PATH/dinov2/dinov2/fsdp/__init__.py", line 99, in save
    data["model"] = self.model.state_dict()
  File "PATH/dinovenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1818, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)  
 File "PATH/dinovenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1818, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "PATH/dinovenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1815, in state_dict
    self._save_to_state_dict(destination, prefix, keep_vars)
  File "PATH/dinovenv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1722, in _save_to_state_dict
    hook(self, prefix, keep_vars)
  File "PATH/dinovenv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context                                                                                                                                                                                          
    return func(*args, **kwargs)
  File "PATH/dinovenv/lib/python3.10/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 669, in _pre_state_dict_hook
    _pre_state_dict_hook_fn[fsdp_state._state_dict_type](
  File "PATH/dinovenv/lib/python3.10/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 359, in _local_pre_state_dict_hook
    raise RuntimeError(
RuntimeError: ``local_state_dict`` can only be used when parameters are flatten and sharded.
```

**Comment by JeremyMorlier** [comment]
You may notice that if you are using a single node, Dino will automatically revert to using normal data parallelism instead of fully sharded. In this case, you may still get the local_state_dict error. You can also address this by using a full state dict instead of local state in dinov2/fsdp/__init__.py, changing to `with FSDP.state_dict_type(self.model, StateDictType.FULL_STATE_DICT):` instead of `with FSDP.state_dict_type(self.model, StateDictType.LOCAL_STATE_DICT):`

_Originally posted by @sfilios in https://github.com/facebookresearch/dinov2/issues/134#issuecomment-1623629263_

_Originally posted by @dqgdqg in https://github.com/facebookresearch/dinov2/issues/273#issuecomment-1772265634_
